//
//  CTVFLTransaction.h
//  CTVFL
//
//  Created on 2019/3/29.
//

#import <Foundation/Foundation.h>

#if TARGET_OS_OSX
#import <Cocoa/Cocoa.h>
#endif

#if TARGET_OS_IOS || TARGET_OS_TV
#import <UIKit/UIKit.h>
#endif

NS_ASSUME_NONNULL_BEGIN

@class CTVFLEvaluationContext;

/// A transaction object collects constraints generated by CTVFL.
///
/// Implicit Transaction v.s. Explicit Transaction
/// ==============================================
/// `CTVFLTransaction` runs an implicit transaction for each thread. But
/// this transaction does not collect constraints unless you use those
/// "enforcing" API to add constraints to the transaction.
///
/// When you called `+begin` and `+commit`, you opened up an explicit
/// transaction. Explicit collects all the constraints generated inside
/// it. Since CTVFL drives transactions with RunLoop, the collected
/// constraints would be released in next loop of the RunLoop.
///
@interface CTVFLTransaction : NSObject
#pragma mark Managing Transaction Stack

+ (void)begin;

+ (void)commit;

#pragma mark Managing Constraints

@property (nonatomic, class, copy, readonly) NSArray<NSLayoutConstraint *> * constraints;

+ (void)addConstraint:(NSLayoutConstraint *)constraint;

+ (void)addConstraint:(NSLayoutConstraint *)constraint enforces:(BOOL)enforces;

+ (void)addConstraints:(NSArray<NSLayoutConstraint *> *)constraints;

+ (void)addConstraints:(NSArray<NSLayoutConstraint *> *)constraints enforces:(BOOL)enforces;

// TODO: Add a class property which stores system spacing.

#pragma mark Computational Resources

@property (nonatomic, class, strong, readonly) CTVFLEvaluationContext * sharedEvaluationContext;

@end

NS_ASSUME_NONNULL_END
